### ISSUE TITLE
Getting Group Members on Board

### ISSUE THREAD

**Issue by HIST209** [HIST209/Project#2]
We should get all group members on board, this ticket tracks the progress.

- [x] Member 1
- [x] Member 2
- [x] Member 3
- [x] Member 4
- [x] Member 5

**Comment by HIST209** [comment]
@nghaffar21 we can get some help from you on this :)

**Comment by YahyaElnouby26** [comment]
Hello

**Comment by nghaffar21** [comment]
What a picture😂😂😂😂

**Comment by Mastavor** [comment]
gentlemen and gentlemen now introducinggg *drum roll*

Member #4

**Comment by HIST209** [comment]
welcome comrade, as a fellow communist we hope you can share your shitposts with us

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Mastavor** [comment]
anything for the motherland

**Comment by HIST209** [comment]
@Mastavor wait is ur name mani?

**Comment by Mastavor** [comment]
@HIST209 yeah it is, whatcha thought it was

**Comment by HIST209** [comment]
@Mastavor oh since i just realized its meaning in arabic xD

**Comment by Mastavor** [comment]
well we all are sperm in a way, i just chose to embrace my nature

**Comment by HIST209** [comment]
😂😂😂

**Comment by HIST209** [comment]
Boomers we still need to chain the other bro on here, can anyone guide him through so that we meet our first deadline?

**Comment by KneeGrows12** [comment]
👋🏿 👋🏿 👋🏿

**Comment by nghaffar21** [comment]
Welcome brother man👊🏾

**Comment by HIST209** [comment]
First deadline met, good work everyone!
